### ISSUE TITLE
[Feature]: Log to file

### ISSUE THREAD

**Issue by mabushey** [SkwalExe/rust-logging#2]
### Contact Details

rust-logging@sendthemtomir.com

### Feature Description

I love how simple this is. I need to be able to display which this does, but also write to a log file. I'm currently using pretty-env-logger, but this also is lacking in logging [to a file]. One thing I like about pretty-env-logger is you can set env vars such as RUST_LOG=debug to get debug output.

### Problem Solved

Writing a log file.

**Comment by SkwalExe** [comment]
hey @mabushey you have a good idea ! I'm working on it !

**Comment by mabushey** [comment]
I also run Arch. :)

**Comment by SkwalExe** [comment]
Hello @mabushey you can check #3
I added a feature to log to a file, I hope this is what you needed. :)

https://github.com/SkwalExe/rust-logging/tree/v0.2.0#log-file-

**Comment by mabushey** [comment]
Thank you! It's very close. I need to display and log. What would be ideal is if the log file is not set it prints to the screen, and if you set the log file it outputs to both. Having the fxxx functions to only output to the log file is not a bad idea.

**Comment by SkwalExe** [comment]
I will add a feature to print to the file and on the terminal when an environment variable is set :)

**Comment by SkwalExe** [comment]
You can now set the `LOG` env variable to `print` to also print to the terminal when logging to a file 

see #4 
https://github.com/SkwalExe/rust-logging#also-logging-to-terminal-when-logging-to-file-
